### ISSUE TITLE
[FR] Improve the text input in Settings

### ISSUE THREAD

**Issue by tjg23** [Darren-project/obsidian-kv#3]
At the moment, the text input in the plugin’s settings page is small, and the plugin’s parsing seems to remove newlines and indentation which makes it slightly more difficult/tedious to edit the data. 
A good example of the sort of improvements I think would be beneficial is the [Latex Suite plugin](https://github.com/artisticat1/obsidian-latex-suite) by artisticat1. It uses data in a similar format, and it has an editor in the settings page that is larger, maintains formatting, and features syntax highlighting. 
This is not super important, since I primarily see myself editing the data through JS, but it would be a nice QOL improvement

**Comment by darrenwjlau** [comment]
Sorry that I just saw this
Was busy building my infra

**Comment by darrenwjlau** [comment]
Can you point me to the settings design please

**Comment by darrenwjlau** [comment]
@tjg23

**Comment by tjg23** [comment]
Sure, the code for Latex Suite's settings implementation is [here](https://github.com/artisticat1/obsidian-latex-suite/tree/main/src/settings). I've only spent a few minutes looking at it, and it seems fairly complex, but the first thing that stands out to me is that artisticat's design uses a codemirror EditorView instead of a simple text area

**Comment by darrenwjlau** [comment]
It is finally done
![image](https://github.com/user-attachments/assets/8af9e0e8-02e3-4607-829f-9ab092aa55ba)

**Comment by darrenwjlau** [comment]
@tjg23

**Comment by tjg23** [comment]
Very cool!

**Comment by darrenwjlau** [comment]
Thanks
